from __future__ import annotations

from typing import Any

import polars as pl

TABLE_KEYS: dict[str, list[str]] = {
    "posts": ["post_id"],
    "propagations": ["propagation_id"],
    "propagation_edges": ["propagation_id"],
    "comments": ["comment_id"],
    "comment_edges": ["comment_id"],
    "authors": ["author_id"],
    "media_refs": ["media_id"],
    "collection_runs": ["run_id"],
}

TABLE_SCHEMAS: dict[str, dict[str, Any]] = {
    "posts": {
        "post_id": pl.String,
        "platform": pl.String,
        "source_id": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "origin_permalink": pl.String,
        "propagation_kind": pl.String,
        "is_propagation": pl.Boolean,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "shares": pl.Int64,
        "comments_count": pl.Int64,
        "views": pl.Int64,
        "forwards": pl.Int64,
        "reply_count": pl.Int64,
        "has_media": pl.Boolean,
        "media_type": pl.String,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "propagations": {
        "propagation_id": pl.String,
        "platform": pl.String,
        "source_id": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "origin_permalink": pl.String,
        "propagation_kind": pl.String,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "shares": pl.Int64,
        "comments_count": pl.Int64,
        "views": pl.Int64,
        "forwards": pl.Int64,
        "reply_count": pl.Int64,
        "has_media": pl.Boolean,
        "media_type": pl.String,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "propagation_edges": {
        "propagation_id": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "propagation_kind": pl.String,
        "platform": pl.String,
        "run_id": pl.String,
    },
    "comments": {
        "comment_id": pl.String,
        "platform": pl.String,
        "parent_post_id": pl.String,
        "parent_entity_type": pl.String,
        "parent_entity_id": pl.String,
        "parent_comment_id": pl.String,
        "reply_to_message_id": pl.String,
        "thread_root_post_id": pl.String,
        "origin_post_id": pl.String,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "depth": pl.Int64,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "comment_edges": {
        "comment_id": pl.String,
        "parent_post_id": pl.String,
        "parent_entity_type": pl.String,
        "parent_entity_id": pl.String,
        "parent_comment_id": pl.String,
        "reply_to_message_id": pl.String,
        "thread_root_post_id": pl.String,
        "origin_post_id": pl.String,
        "depth": pl.Int64,
        "run_id": pl.String,
    },
    "authors": {
        "author_id": pl.String,
        "name": pl.String,
        "profile_url": pl.String,
        "source_collector": pl.String,
        "run_id": pl.String,
    },
    "media_refs": {
        "media_id": pl.String,
        "owner_post_id": pl.String,
        "media_type": pl.String,
        "title": pl.String,
        "url": pl.String,
        "preview_url": pl.String,
        "run_id": pl.String,
    },
    "collection_runs": {
        "run_id": pl.String,
        "collected_at": pl.String,
        "collector": pl.String,
        "mode": pl.String,
        "status": pl.String,
        "fallback_used": pl.Boolean,
        "warning_count": pl.Int64,
        "warning_messages": pl.List(pl.String),
        "post_count": pl.Int64,
        "propagation_count": pl.Int64,
        "comment_count": pl.Int64,
        "platform": pl.String,
        "source_id": pl.String,
        "source_name": pl.String,
        "source_type": pl.String,
        "discussion_linked": pl.Boolean,
        "filtered_service_message_count": pl.Int64,
        "source_run_count": pl.Int64,
        "source_run_ids": pl.List(pl.String),
    },
}
